[package]

name = "chamkho"
version = "0.0.5"
authors = ["Vee Satayamas <vsatayamas@gmail.com>"]
description = "Thai word segmentation/breaking library and command line"
documentation = "https://github.com/veer66/chamkho/blob/master/README.md"
homepage = "https://github.com/veer66/chamkho/"
repository = "https://github.com/veer66/chamkho.git"
readme = "README.md"
keywords = ["text", "nlp", "lao", "thai", "library"]
license = "BSD-2-Clause"

[[bin]]
name = "wordcut"
path = "src/cli.rs"
